# Site settings
title: Michael
email: 13240368231@163.com
description: Michael的博客 Web

 baseurl: "http://michaelxu001.github.io/MichaelXu001.io" 
url: "http://yourdomain.com" 
twitter_username: jekyllrb
github_username:  github
permalink: /:year/:month/:day/:title/

# Build settings

paginate: 10
paginate_path: "page:num"


# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
