# Site settings
title: Michael
email: 13240368231@163.com
description: Michael的博客 Web
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

 baseurl: "http://michaelxu001.github.io/MichaelXu001.io/" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  github
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"


# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
